spring.application.name=spring-boot-notes-api
spring.datasource.url=jdbc:postgresql://localhost:5332/notes
spring.datasource.password=password
spring.datasource.username=boost
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true